version: '3.4'

services:
  main:
    build:
      context: ..
      dockerfile: ./Dockerfile
      network: host
    image: tornio
    expose:
      - '4182'
    volumes:
      - './:/app'
    working_dir: /app
    # stdin_open: true
    # tty: true
    ports:
      - 4182:4182
